### ISSUE TITLE
Release new major version (feature list)

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1770]
**Also, a number of "breaking changes" had been discussed to go in the next major release:**

- [x] [pdcastro] Update `balena-sdk` to v13, which requires dropping Node 8 support (#1742)
- [x] [pdcastro] Update `pkg` to v4.4.8 (drops support for Node 8)
- [x] [pdcastro] Update `@balena/lint` to `^5.0.0` (uses prettier v2 which does not work with Node 8)

**Doable with "feature switches":**

- [x] [pdcastro] Have `--nogitignore` be the default for balena push/build/deploy (drop support for `gitignore` - issues #1032 and #1148)
- [x] [srlowe] Have the ‘--all’ option be the default behaviour of ‘balena envs’
- [x] [pdcastro] Have the ALIASES column show by default in the output of `devices supported`
- [x] [pdcastro] Have the SLUG column show by default in the output of `balena apps`
- [x] [pdcastro] Promote project validation check for ‘docker-compose.yml’ in parent folder from warning to error.
- [x] [srlowe] Have `--convert-eol` be the default behaviour of ‘balena push’, ‘build’, ‘deploy’
- [x] [pdcastro] Have “--logs” by default in `balena build` or `balena deploy --build`, because some build errors are hidden without that option, leading to support queries.
- [x] [srlowe]: Remove ID from `tags` result (ID not useful/usable).

- [x] [srlowe] Improve error message when not logged in. Currently it is:
> _You have to log in to continue_
> _Run the following command to go through the login wizard:_
> 	_$ balena login_

I think it would be nicer to have something like:
> _Login required: use the “balena login” command to log in._

**Changes that are not breaking, and don't need to be part of v12 release:**
- [x] [srlowe]: Consolidate all 4 `public-url` commands to one.
- [ ] [srlowe] ~~`env rename` should be changed to `env set`, because it changes a variable’s value rather than its name (ref: #1414)~~ Let's add `env set`, and document `env rename` as an alias to `env set`. This doesn't have to be a breaking change.

**Changes not being made:** (at this time)
- ~~[srlowe]: Consider `tag set` -> `tag add`~~ (doesn't really make sense with `env set` since change was for consistency)
- ~~[pdcastro] Update [net-keepalive](https://www.npmjs.com/package/net-keepalive) to v1.3.1 (or later), which adds support for Node 14 but drops support for Node 8.~~ Skipped for now because we found that this requires **Node.js >= 10.20.0,** while:
  - The standalone zip packages ([pkg](https://www.npmjs.com/package/pkg)) currently bundle Node.js v10.17.0.
  - The native/graphical installer for macOS currently bundles Node.js v10.16.0.
  - The native/graphical installer for Windows currently bundles Node.js v10.19.0.

**Comment by srlowe** [comment]
> Login required: use the “balena login” command to log in. 
:+1:

**Comment by pdcastro** [comment]
Internal discussion: https://www.flowdock.com/app/rulemotion/i-cli/threads/FRBX9dsvl9HbdU-A2JM9dSzpfgq
